### ISSUE TITLE
Compress link URL

### ISSUE THREAD

**Issue by Iain-S** [Iain-S/HiFiDrawJS#4]
We used to show the full link URL so that users can see how it is constructed.  However, now that we escape the chars in it, it no longer looks very good and is not readable. 

Use something like lz-string to compress urls before escaping them.

**Comment by chriswrightft** [comment]
Not sure lz-string would help in this situation due to it outputting a longer string than what you start with. Used this demo URL - http://pieroxy.net/blog/pages/lz-string/demo.html
-> "Hello World".length
-> 11
converts to
-->"85 04 36 30 f6 60 40 00 90 ea 30 27 c8 04 00 00".length
-->47

**Comment by Iain-S** [comment]
Thanks Chris,  

You're quite right, lz-string doesn't do a good job or shortening our URLs and often makes them longer.  I'm going to close the issue and, at some point, might put the permalink in a PaperCSS collapsible instead.  

Cheers

Iain
